version: '3.8'
services:
 react-app:
   container_name: react-todo
   build:
     context: .
     dockerfile: Dockerfile
   volumes:
     - ./:/src
   command: sh -c "cd app && PORT=3001 yarn start"
   ports:
     - "3001:3001"
   stdin_open: true